config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'commission#home'

  get '/home',					to: 'commission#home'
  post '/commission/create',	to: 'commission#create', 	as: 'create_commission'
  post '/event/search', 		to: 'event#search', 		as: 'event_show'
  post '/user/search', 			to: 'user#search', 			as: 'user_show'
  post '/booking/create',		to: 'booking#create',		as: 'create_booking'
  resources :commission
  resources :event
  resources	:user
  resources :booking
end

app/models/commission.rb
class Commission < ApplicationRecord
	belongs_to	:user,			optional: true
	belongs_to	:event,			optional: true
	belongs_to	:booking,		optional: true

	validates		:card,
							:deposit,		numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/commission_controller.rb
class CommissionController < ApplicationController
  def home
  end

  def new
    @commission = Commission.new
  end

  def create
    @commission = Commission.new(card: params[:commission][:card],
                                deposit: params[:commission][:deposit]
                                )
    case params[:commission][:type] 
    when "0"
    	@commission.booking_id = params[:commission][:id]
    when "1"
    	@commission.event_id 	= params[:commission][:id]
    	if Event.exists?(params[:commission][:id])
    		event = Event.find(params[:commission][:id])
    		event.hasCommission = true
        event.save
    	end
    else
    	@commission.user_id = params[:commission][:id]
    	if User.exists?(params[:commission][:id])
    		user = User.find(params[:commission][:id])
    		user.hasCommission = true
        user.save
    	end
    end
    if @commission.save
      flash.now[:success] = "Commission personalizada"
    else
      flash.now[:error] = "Commission no guardada"
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    if Commission.exists?(params[:id])
      commission = Commission.find(params[:id])

      if commission.event_id != nil 
        event = Event.find(commission.event_id)
        event.hasCommission = false
        event.save

      elsif commission.user_id != nil
        user = User.find(commission.user_id)
        user.hasCommission = false
        user.save
      end

  		commission.destroy
      flash[:success] = "Comisión eliminada"
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/commission_helper.rb
module CommissionHelper
end

app/views/commission/_custom_form.html.erb
<div class= 'customize_commission' style="display: none">
	<h3>Personalizar comisión</h3>
	<%=form_for :commission , url: create_commission_path  do |f|%>

    <p>Indica las nuevas comisiones por depósito y por tarjeta:</p>

    <div class= "input-commission col-sm-11 col-sm-offset-1">

	    <div class="row">
	    	<div class= "col-sm-8 col-sm-offset-2">
		    	<div class="col-sm-2"><p>Depósito:</p></div>

		   		<div class="col-sm-6">
			   		<div class="input-group">
						  <span class="input-group-addon">$</span>
						 	 <%= f.text_field :deposit, value: 10.00, required: true,  class: "form-control", onkeypress: "return isNumberKeyorPoint(event)"%>
						</div>
					</div> 
				</div>
	    </div>

	    <div class="row">
	    	<div class= "col-sm-8 col-sm-offset-2">
		    	<div class="col-sm-2"><p>Tarjeta:</p></div>

		   		<div class="col-sm-6">
		   			<div class="input-group">
						 	<%= f.text_field :card, value: 3.5, required: true, class: "form-control", onkeypress: "return isNumberKeyorPoint(event)"%>
						  <span class="input-group-addon">%</span>
						</div>				 	 
					</div>
				</div>
    	</div>
    </div>

    <%= f.hidden_field :type, value: @type%></p>
    <%= f.hidden_field :id, value: params[:id]%></p>
    <br>
    <div class= "row"><p>*Nota: Las comisiones son por ticket.</p></div>
    <div class= "row">
	   	<button type='button' id= "btn-cancel" class="btn btn-cstom btn-event">Cancelar</button>
	    <%= f.submit("Personalizar", class: "btn btn-cstom btn-event") %>
    </div>
	<%end%>
</div>

app/views/commission/home.html.erb
<div class="jumbotron">
  <h2 class= "text-center">Módulo para personalizar comisiones</h2>
  <p class= "text-center">para Boletia</p>
  <div class= "text-center"><%= image_tag "boletia_logo"%></div> 
</div>

<div class="row seekers">
	<div class="col-sm-12">
		<div class="col-sm-5 col-sm-offset-1">
				<%= render partial: 'event/search'%>
		</div>
		<div class="col-sm-5 ">
				<%= render partial: 'user/search'%>
		</div>
	</div>
</div>