config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'commission#home'

  get '/home',					to: 'commission#home'
  post '/commission/create',	to: 'commission#create', 	as: 'create_commission'
  post '/event/search', 		to: 'event#search', 		as: 'event_show'
  post '/user/search', 			to: 'user#search', 			as: 'user_show'
  post '/booking/create',		to: 'booking#create',		as: 'create_booking'
  resources :commission
  resources :event
  resources	:user
  resources :booking
end

app/models/event.rb
class Event < ApplicationRecord
	
	has_many		:bookings
	has_one			:commission
	belongs_to	:user

	validates		:name, 				presence: true, 
														length: { maximum: 50 }
	
	validates		:place,
							:category,
							:date_event,	presence: true
	
	validates 	:assistance, 	numericality: { only_integer: true, 
																						greater_than: 0, 
																						less_than_or_equal_to: 50000 }
	
	validates		:description,	length: { maximum: 500 }

	validate		:future_date

	private

		def future_date
			errors.add("Event date can't be in the past") if self.date_event != nil && self.date_event < Date.today	
		end							

end

app/controllers/event_controller.rb
class EventController < ApplicationController

	def search
		if params[:event_id] != nil && params[:event_id] != ""
			id = params[:event_id]
			redirect_to event_path(id)
		end
	end

	def show
		if Event.exists?(params[:id])
				@event = Event.find(params[:id])
				@user = User.find(@event.user_id).name
				@status = true
				flash.now[:success] = "¡Evento encontrado!"				
		else
				@status = false
				flash.now[:danger]	= "¡Evento no encontrado!"
		end
	end

	def destroy
	end

end

app/helpers/event_helper.rb
module EventHelper
end

app/views/event/_search.html.erb
<div class = "seeker">
	<div class = "title-seeker text-center">
		<h4> Buscador por Evento</h4>
	</div>

	<div class="form-group form-seeker">

		<%=form_tag event_show_path, method: :post do%>

			<div class="row">
			<div class="col-sm-10 col-sm-offset-1">
					<div class="col-sm-1 text-center">
					 	<h4>id:</h4>
					</div>

					<div class="col-sm-10">			
						<%= text_field_tag 'event_id', nil, placeholder: 'Ingresa el id del evento..', required: true, class: "form-control", onkeypress: "return isNumberKey(event)"%>
					</div>				
				</div>
			</div>	
			<br>
			<div class="row">
			<div class="col-sm-8 col-sm-offset-2">
				 	<%=submit_tag("Buscar", class: "btn btn-block")  %>
				</div>
			</div>
		<%end%>

	</div>
</div>

app/views/event/show.html.erb
<div class = "row">
	<div class = "col-sm-8 col-sm-offset-2">

			<% if @status%>
		<div class="event-group">	

				<div class = "title-event text-center">
					<h3>Evento:  <%= @event.name%></h3>
				</div>
				<br>
				<div class= "event-data text-center">
					<p>#ID: <%= @event.id%></p>
					<p><%= @event.category%></p>
					<p>En <%= @event.place%></p>
					<p>el día <%= @event.date_event%></p>
					<p>Descripción: <%= @event.description%></p>
					<p>Organizado por: <%= @user%></p>
				</div>
				<br>
				<div class = "event-buttons commission-btn text-center">
					<% if @event.hasCommission %>
						<button type='button' class='btn bt-cstm btn-event'><%= link_to "Eliminar comisión personalizada", 
			      { controller: 'commission', action: 'destroy', id: @event.commission.id }, data:
			      { confirm: "¿Estás seguro de eliminar la comisión personalizada?", 
			      	method: :delete, remote: false}%></button>
					<%else%>
					<button type='button' id='customize' class='btn btn-cstm btn-event'>Personalizar comisión</button>
						<%= render 'commission/custom_form',
						object: @type = '1' %>
					<%end%>
				</div>					
		</div>
		<br><br>
			<div class= "row">
				<div class = "col-sm-6 event-buttons return-btn text-center">
						<button type='button' id='btn-return' class='btn btn-cstm btn-event'><%=link_to "Regresar a Inicio", root_path %></button>
				</div>
				<div class = " col-sm-6 event-buttons simulation-btn text-center">
					<button type='button' id='btn-simulate' class='btn btn-cstm btn-event'><%=link_to "Simular compra", new_booking_path(:event => @event.id) %></button>
				</div>
			</div>

		<%else%>
			<div class="event-no-found">
	 			<div class="row text-center">
	 				<div class="col-sm-12">
	 					<h4>El evento que indicaste no pudo ser encontrado. Por favor, intenta otra vez.</h4>
	 				</div>
	 				<div class="row">
		 				<div class="col-sm-10 col-sm-offset-1">	
		 					<%= render partial: 'event/search'%>
		 				</div>
	 				</div>
	 				<br>
	 				<div class = "event-buttons return-btn text-center">
						<button type='button' id='btn-return' class='btn btn-cstm btn-event'><%=link_to "Regresar a Inicio", root_path %></button>
					</div>
	 			</div>
	 		</div>
		<%end%>				
	</div>
</div>