config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'commission#home'

  get '/home',					to: 'commission#home'
  post '/commission/create',	to: 'commission#create', 	as: 'create_commission'
  post '/event/search', 		to: 'event#search', 		as: 'event_show'
  post '/user/search', 			to: 'user#search', 			as: 'user_show'
  post '/booking/create',		to: 'booking#create',		as: 'create_booking'
  resources :commission
  resources :event
  resources	:user
  resources :booking
end

app/models/user.rb
class User < ApplicationRecord

	before_save   :downcase_email

	has_many	:events
	has_one		:commission

	validates	:name, 		presence: true, length: { maximum: 50 }

	validates	:address, presence: true

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :email, 	presence: true, length: { maximum: 255 },
                    	format: { with: VALID_EMAIL_REGEX },
                    	uniqueness: { case_sensitive: false }

  validates :phone,		presence: true,
  										length: {maximum: 20}, if: :its_number?

  VALID_ACCOUNT_REGEX = /\d{4}-\d{4}-\d{4}-\d{4}/

  validates :account, presence: true,
  										format: {with: VALID_ACCOUNT_REGEX}
    private

	    # Converts email to all lower-case.
	    def downcase_email
	      self.email = email.downcase
	    end

	    def its_number?
	    	if self.phone != nil
	    		self.phone.to_i == self.phone.gsub(/\D/,'').to_i
	    	end
	    end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def search
		if params[:user_id] != nil && params[:user_id] != ""
			id = params[:user_id]
			redirect_to user_path(id)
		end
	end

	def show
		if User.exists?(params[:id])
				@user = User.find(params[:id])
				@status = true
				flash.now[:success] = "¡Usuario encontrado!"				
			else
				@status = false
				flash.now[:danger]	= "¡Usuario no encontrado!"
			end
	end
	
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_search.html.erb
<div class = "seeker">
	<div class = "title-seeker text-center">
		<h4> Buscador por Usuario</h4>
	</div>

	<div class="form-group form-seeker">

		<%=form_tag user_show_path, method: :post do%>

			<div class="row">
			<div class="col-sm-10 col-sm-offset-1">
					<div class="col-sm-1 text-center">
					 	<h4> id:</h4>
					</div>

					<div class="col-sm-10">			
						<%= text_field_tag 'user_id', nil, placeholder: 'Ingresa el id del usuario..',required: true, class: "form-control", onkeypress: "return isNumberKey(event)"%>
					</div>				
				</div>
			</div>	
			<br>
			<div class="row">
			<div class="col-sm-8 col-sm-offset-2">
				 	<%= submit_tag("Buscar", class: "btn btn-block")  %>
				</div>
			</div>
		<%end%>

	</div>
</div>

app/views/user/show.html.erb
<div class = "row">
  <div class = "col-sm-8 col-sm-offset-2"> 
    <% if @status%>
      <div class="user-group">	

        <div class = "title-user text-center">
          <h3>Usuario: <%= @user.name%></h3>
        </div>
        <br>
    		<div class= "user-data text-center">
      		<p>#ID: <%= @user.id%></p>
      		<p>email:<%= @user.email %></p>
    		</div>
        <br>
    		<div class = "event-buttons commission-btn text-center">
    		<% if @user.hasCommission %>
    			<button type='button' class='btn bt-cstm btn-event'><%= link_to "Eliminar comisión personalizada", 
          { controller: 'commission', action: 'destroy', id: @user.commission.id }, data:
          { confirm: "¿Estás seguro de eliminar la comisión personalizada?", 
          	method: :delete, remote: false} %></button>
    		<%else%>
    			<button type='button' id='customize' class='btn btn-cstm btn-event'>Personalizar comisión</button>
    			<%= render 'commission/custom_form',
    			object: @type = '2' %>

    		<%end%>
  		</div>
      <br>
     <div class= "events-user">  
   <h3>Eventos que ha organizado este usuario:</h3>
   <br>
   <table class="table">
    <thead>
      <tr>
        <th>#ID</th>
        <th>Nombre</th>
        <th>Mas detalles</th>
        <th></th>
      </tr>
    </thead>
    <% if @user.events.length <= 0 %>
      </table>
      <h5>¡Ups! Aún no tiene eventos organizados</h5>  
    <% else %>
      <tbody>
        <% @user.events.each do |event| %>
          <tr>
            <td><%=event.id%></td>
            <td><%=event.name%></td>
            <td><%=link_to 'Detalles',event_path(event) %></td>
            <td><button type='button' id='btn-simulate' class='event-buttons simulation-btn btn btn-cstm'><%=link_to "Simular compra", new_booking_path(event: event.id) %></button></td>
          </tr>
        <% end %>
      </tbody>
      </table>
    <% end %> 
    <div class = "event-buttons return-btn text-center">
            <button type='button' id='btn-return' class='btn btn-cstm btn-event'><%=link_to "Regresar a Inicio", root_path %></button>
          </div>
  </div>
</div>
    <%else%>
     <div class="event-no-found">
        <div class="row text-center">
          <div class="col-sm-12">
            <h4>El usuario que indicaste no pudo ser encontrado. Por favor, intenta otra vez.</h4>
          </div>
          <div class="row">
            <div class="col-sm-10 col-sm-offset-1"> 
              <%= render partial: 'user/search'%>            
            </div>
          </div>
          <br>
          <div class = "event-buttons return-btn text-center">
            <button type='button' id='btn-return' class='btn btn-cstm btn-event'><%=link_to "Regresar a Inicio", root_path %></button>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>