config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'commission#home'

  get '/home',					to: 'commission#home'
  post '/commission/create',	to: 'commission#create', 	as: 'create_commission'
  post '/event/search', 		to: 'event#search', 		as: 'event_show'
  post '/user/search', 			to: 'user#search', 			as: 'user_show'
  post '/booking/create',		to: 'booking#create',		as: 'create_booking'
  resources :commission
  resources :event
  resources	:user
  resources :booking
end

app/models/booking.rb
class Booking < ApplicationRecord
	has_one		:commission
	belongs_to	:event

	validates	:payment_method,		presence:true

	validates	:price_ticket,
						:ticket_quantity,
						:ticket_commission,
						:total_commission,
						:total_price,				numericality: { greater_than: 0 }
	
	validates	:ticket_quantity,		numericality: { only_integer: true }

	def self.estimate_t_commission(price,quantity,ticket_commission, payment_method)
		if payment_method == 'card'
			price * quantity * (ticket_commission/100)

		elsif payment_method == 'deposit'
			quantity * ticket_commission

		else
			0.0
		end
	end

	def self.estimate_total(price,quantity,total_commission)
		price * quantity + total_commission
	end

end

app/controllers/booking_controller.rb
class BookingController < ApplicationController

	def new
		@booking = Booking.new()
		@event = Event.find(params[:event])
	end

	def create
		event_id = params[:booking][:event_id]
		@booking = Booking.new( price_ticket: 		params[:booking][:price_ticket],
														ticket_quantity: 	params[:booking][:ticket_quantity],
														payment_method: 	params[:booking][:payment_method],
														event_id: 				event_id)
													 
		@commission = check_custom_commission(event_id) ? check_custom_commission(event_id) : default_commission(@booking.id)

		if @booking.payment_method == 'card'
			@booking.ticket_commission = @commission.card
		elsif @booking.payment_method == 'deposit'
			@booking.ticket_commission = @commission.deposit
		end

		@booking.total_commission = Booking.estimate_t_commission(@booking.price_ticket,
																															@booking.ticket_quantity,
																															@booking.ticket_commission, 
																															@booking.payment_method).round(2)

		@booking.total_price = Booking.estimate_total(@booking.price_ticket,
																									@booking.ticket_quantity,
																									@booking.total_commission).round(2)
		# puts '******************TOTALES'
		# puts @booking.total_commission
		# puts @booking.total_price	

		@booking.save

		unless has_custom_commission?(event_id)
			@commission.booking_id = @booking_id 
			@commission.save
		end

		#redirect_to booking_path(@booking, format: :pdf)
		redirect_to booking_path(@booking)

	end

	def show
		# create_pdf(params[:id])
	end

	private

		def has_custom_commission?(event_id)
			if Event.exists?(event_id)
				event = Event.find(event_id)
				user 	= User.find(event.user_id)

				if event.hasCommission || user.hasCommission
					true
				end
			end
			false
		end

		def check_custom_commission(event_id)
			if 	Event.exists?(event_id)

				event = Event.find(event_id)
				if event.hasCommission
					event.commission
				else
					user = User.find(event.user_id)
					if  user.hasCommission
						user.commission
					else
						false
					end
				end

			end
		end

		def default_commission(booking_id)
			 c = Commission.create(booking_id: booking_id)
		end

		def create_pdf(booking)
      respond_to do |format|
      format.html
      format.pdf do
        @example_text = "some text"
        render :pdf => "booking",
               :template => "booking/booking.pdf.erb",
               :layout => "pdf.html",
               :footer => {
                    # :center => "Center",
                    # :left => "Left",
                    # :right => "Right"
                 }
      end
    end
    end

end

app/helpers/booking_helper.rb
module BookingHelper
end

app/views/booking/booking.pdf.erb
<%= wicked_pdf_stylesheet_link_tag "documents" %>

	<% booking = Booking.find(params[:id])%>
	<div class = "booking_summarize">

		<div class = "title-booking text-center">
			<h2>Boletia</h2>  	
		</div>

		<div>
		<%event = Event.find(booking.event_id)%>
			<h2>Resumen de la Reservación</h2>	
			<h3> para <%=event.name%></h3>
		</div>

		<div class = "booking-details">
		<table>
		  <tr>
		    <th></th>
		    <th></th>
		  </tr>

		  <tr>
		    <td>Cantidad de boletos:</td>
		    <td><%=booking.ticket_quantity%></td>
		  </tr>

		  <tr>
		    <td>Precio unitario:</td>
		    <td>$<%=booking.price_ticket%></td>
		  </tr>

		  <tr>
		    <td> Método de pago:</td>
				<%if booking.payment_method == 'card'%>
		    	<td>Tarjeta</td>
				<% else %>
					<td>Depósito</td>
				<% end %>
		  </tr>

		  <tr>
		    <td>Comisión por boleto:</td>
		    <td>$<%=booking.ticket_commission%></td>
		  </tr>

		  <tr>
		    <td>Comisión total:</td>
		    <td>$<%=booking.total_commission%></td>
		  </tr>

		   <tr>
		    <td><strong>Precio total:</strong></td>
		    <td><strong>$<%=booking.total_price%></strong></td>
		  </tr>
		</table>			
		<br>
		</div>
</div>

app/views/booking/new.html.erb
<div class = "row">
  <div class = "col-sm-10 col-sm-offset-1"> 

		<div class="booking-group">	

			<div class="title-booking text-center">
			  <h3>Simulador de compra </h3>
			  <h3><small> para el evento <%=@event.name%></small></h3>
			</div>
			<br>

			<div class="booking-form">
				
				<%= form_for :booking, url: create_booking_path do |f|%>

					<div class="row">
						<div class= "col-sm-8 col-sm-offset-2"> 
							<div class="col-sm-3 text-center"><p>Precio del Boleto:</p></div>

							<div class="col-sm-9">
								<div class="input-group">
							  	<span class="input-group-addon">$</span>
									<%= f.text_field :price_ticket, value: nil, placeholder: "Precio por boleto", required: true, class: "form-control", onkeypress: "return isNumberKeyorPoint(event)"%>							 	 
								</div>
							</div>
						</div>
					</div>
					<br>
					<div class="row">
						<div class= "col-sm-8 col-sm-offset-2"> 
							<div class="col-sm-3 text-center"><p>Cantidad de Boletos:</p></div>

							<div class="col-sm-9">
								<%= f.text_field :ticket_quantity, value: nil, placeholder: "Cantidad de boletos", required: true, class: "form-control", onkeypress: "return isNumberKey(event)"%>
							</div>
						</div>
					</div>
					<br>
					<div class="row">
						<div class= "col-sm-8 col-sm-offset-2"> 			
							<div class="col-sm-3 text-center"><p>Método de pago:</p></div>

							<div class="col-sm-9 ">
								<%= f.select (:payment_method) do%>
									<% [['Tarjeta', 'card'], ['Depósito', 'deposit']].each do |c| -%>
					    		<%= content_tag(:option, c.first, value: c.last) %>
					  			<% end %>
								<% end %>
							</div>
						</div>
					</div>
					<br>			
					<div class="row text-center">
						<%=	f.hidden_field :event_id, value: @event.id%>
						<button type='button' id='btn-return' class='btn btn-cstm btn-event'><%=link_to "Regresar", event_path(@event.id) %></button>

						<%= f.submit "Calcular precio para reservar", class: "btn btn-cstm btn-event"%>					
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/booking/show.html.erb
	<% booking = Booking.find(params[:id])%>
	<div class = "booking_summarize">

		<div class = "title-booking text-center">
			<h2>Boletia</h2>  	
		</div>

		<div>
		<%event = Event.find(booking.event_id)%>
			<h2>Resumen de la Reservación</h2>	
			<h3> para <%=event.name%></h3>
		</div>

		<div class = "booking-details">
		<table>
		  <tr>
		    <th></th>
		    <th></th>
		  </tr>

		  <tr>
		    <td>Cantidad de boletos:</td>
		    <td><%=booking.ticket_quantity%></td>
		  </tr>

		  <tr>
		    <td>Precio unitario:</td>
		    <td>$<%=booking.price_ticket%></td>
		  </tr>

		  <tr>
		    <td> Método de pago:</td>
				<%if booking.payment_method == 'card'%>
		    	<td>Tarjeta</td>
				<% else %>
					<td>Depósito</td>
				<% end %>
		  </tr>

		  <tr>
		    <td>Comisión por boleto:</td>
		    <td>$<%=booking.ticket_commission%></td>
		  </tr>

		  <tr>
		    <td>Comisión total:</td>
		    <td>$<%=booking.total_commission%></td>
		  </tr>

		   <tr>
		    <td><strong>Precio total:</strong></td>
		    <td><strong>$<%=booking.total_price%></strong></td>
		  </tr>
		</table>			
		<br>
		</div>
</div>